import type { Metadata } from "next";
// import { Princess_Sofia } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "./Components/ThemeProvider";
import Footer from "./Components/Footer";

// const fontSans = Princess_Sofia({
//     subsets: ["latin"],
//     variable: "--font-sans",
//     weight: ["400"],
// });
const myFont = localFont({ src: "../fonts/waltograph/waltographUI.ttf" });
export const metadata: Metadata = {
    title: "Look Box",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={cn("min-h-screen bg-background antialiased", myFont.className)}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange>
                    {children}
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
