import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "./Components/ThemeProvider";
import Footer from "./Components/Footer";

const fontSans = Quicksand({
    subsets: ["latin"],
    variable: "--font-sans",
    weight: ["400"],
});

export const metadata: Metadata = {
    title: "Look Box",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={cn("min-h-screen bg-background antialiased", fontSans.className)}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange>
                    {children}
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
